### ISSUE TITLE
OpenGL.GL.shaders.ShaderCompilationError

### ISSUE THREAD

**Issue by Feegooddddd** [liyi14/DeepIM-Honda#2]
Thank you for your excellent works, when I run ' sh test_auto.sh ', I meet the error as follow:
Traceback (most recent call last):
  File "./tools/demo_test.py", line 627, in <module>
    renderer, model_mesh_paths = load_renderer(class_names)
  File "./tools/demo_test.py", line 597, in load_renderer
    model_scale=model_scale)
  File "/home/zyh/DeepIM-Honda-master/ycb_render/ycb_renderer.py", line 119, in __init__
    """, GL.GL_VERTEX_SHADER)
  File "/home/zyh/.conda/envs/pointdsc/lib/python3.7/site-packages/OpenGL/GL/shaders.py", line 241, in compileShader
    shaderType,
OpenGL.GL.shaders.ShaderCompilationError: ("Shader compile failure (0): b'0:2(10): error: GLSL 4.60 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES\\n'", [b'\n        #version 460\n        uniform mat4 V;\n        uniform mat4 P;\n        uniform mat4 pose_rot;\n        uniform mat4 pose_trans;\n        uniform vec3 instance_color; \n                \n        layout (location=0) in vec3 position;\n        layout (location=1) in vec3 normal;\n        layout (location=2) in vec2 texCoords;\n        out vec2 theCoords;\n        out vec3 Normal;\n        out vec3 FragPos;\n        out vec3 Normal_cam;\n        out vec3 Instance_color;\n        out vec3 Pos_cam;\n        out vec3 Pos_obj;\n        void main() {\n            gl_Position = P * V * pose_trans * pose_rot * vec4(position, 1);\n            vec4 world_position4 = pose_trans * pose_rot * vec4(position, 1);\n            FragPos = vec3(world_position4.xyz / world_position4.w); // in world coordinate\n            Normal = normalize(mat3(pose_rot) * normal); // in world coordinate\n            Normal_cam = normalize(mat3(V) * mat3(pose_rot) * normal); // in camera coordinate\n            \n            vec4 pos_cam4 = V * pose_trans * pose_rot * vec4(position, 1);\n            Pos_cam = pos_cam4.xyz / pos_cam4.w;\n            Pos_obj = position;\n            \n            theCoords = texCoords;\n            Instance_color = instance_color;\n        }\n        '], GL_VERTEX_SHADER)

**Comment by Feegooddddd** [comment]
I have solved this error by changing "#version 460 " to "#version 450"
